### ISSUE TITLE
Add Profile Banner To 𝙺𝚊𝚟𝚊#9879

### ISSUE THREAD

**Issue by OnKava** [Discord-Custom-Covers/usrbg#261]
![tumblr_oey060Qf9p1sh05g3o1_400](https://user-images.githubusercontent.com/55412830/132957357-8967358b-7566-4743-8a1c-8361f9d7131d.gif)

**Comment by QbDesu** [comment]
Use the bot on the [Discord server](https://discord.gg/TeRQEPb) instead. 
<https://github.com/Discord-Custom-Covers/usrbg#request-your-own-usrbg>

**Comment by OnKava** [comment]
On Discord it say it is ofline
