### ISSUE TITLE
How to use with OpenAsar ?

### ISSUE THREAD

**Issue by DodoLeDev** [Discord-Custom-Covers/usrbg#279]
Hi everyone!
I'm using UserBG with my profile, and I love the concept of offering alternate Nitro features!
Unfortunately, with the rewrite of the Desktop Discord App, I now use the [OpenAsar](https://openasar.dev/) tool with my install, and UserBG doesn't seem to work in any way with it...

_Do you have any clues how to make it work?_

**Comment by Gabe616** [comment]
try using Vencord, it's a really good mod client for PC
