### ISSUE TITLE
Discord Cdn & Media links will no longer work in usrbg.

### ISSUE THREAD

**Issue by ghost** [Discord-Custom-Covers/usrbg#285]
Discord is now as of the 22nd of February (yesterday) enforcing all media and cdn links to have the expiration parameters on the link (they expire after 7-14 days, so pointless to use them now since you'll have to reupload it every week), any link without them will not work, so 16679 users images will not work, will display no image at all.

**Comment by p0rtL6** [comment]
This is a non-issue anymore as we have migrated image hosting.
