### ISSUE TITLE
Popouts not rendering correctly in current canary w/default theme

### ISSUE THREAD

**Issue by gdude2002** [Discord-Custom-Covers/usrbg#3]
![image](https://user-images.githubusercontent.com/204153/76405681-67672c80-6380-11ea-9f4c-c2935d0755c7.png)

I thought this might've been `revert-discord`'s fault, but removing it and reloading doesn't change much.

Canary 55808.

**Comment by Tropix126** [comment]
Could not reproduce on such build. Try disabling all plugins that might affect the avatar (aside from devilbro plugins). Make sure no transforms are being applied to the avatar as well.

**Comment by gdude2002** [comment]
I can confirm that this is caused by the [Discord Tweaks plugin](https://github.com/NurMarvin/discord-tweaks). Good shout, should've thought of it before!
